Files/core/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MyFatoorahController;


Route::get('/clear', function(){
    \Illuminate\Support\Facades\Artisan::call('optimize:clear');
});

//cron
Route::get('cron', 'CronController@featuredCron')->name('cron');



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


Route::namespace('Gateway')->prefix('ipn')->name('ipn.')->group(function () {
    Route::post('paypal', 'paypal\ProcessController@ipn')->name('paypal');
    // Route::post('myfatoorah', 'myfatoorah\ProcessController@ipn')->name('paypal');
    Route::get('paypal_sdk', 'paypal_sdk\ProcessController@ipn')->name('paypal_sdk');
    Route::post('perfect_money', 'perfect_money\ProcessController@ipn')->name('perfect_money');
    Route::post('stripe', 'stripe\ProcessController@ipn')->name('stripe');
    Route::post('stripe_js', 'stripe_js\ProcessController@ipn')->name('stripe_js');
    Route::post('stripe_v3', 'stripe_v3\ProcessController@ipn')->name('stripe_v3');
    Route::post('skrill', 'skrill\ProcessController@ipn')->name('skrill');
    Route::post('paytm', 'paytm\ProcessController@ipn')->name('paytm');
    Route::post('payeer', 'payeer\ProcessController@ipn')->name('payeer');
    Route::post('paystack', 'paystack\ProcessController@ipn')->name('paystack');
    Route::post('voguepay', 'voguepay\ProcessController@ipn')->name('voguepay');
    Route::get('flutterwave/{trx}/{type}', 'flutterwave\ProcessController@ipn')->name('flutterwave');
    Route::post('razorpay', 'razorpay\ProcessController@ipn')->name('razorpay');
    Route::post('instamojo', 'instamojo\ProcessController@ipn')->name('instamojo');
    Route::get('blockchain', 'blockchain\ProcessController@ipn')->name('blockchain');
    Route::get('blockio', 'blockio\ProcessController@ipn')->name('blockio');
    Route::post('coinpayments', 'coinpayments\ProcessController@ipn')->name('coinpayments');
    Route::post('coinpayments_fiat', 'coinpayments_fiat\ProcessController@ipn')->name('coinpayments_fiat');
    Route::post('coingate', 'coingate\ProcessController@ipn')->name('coingate');
    Route::post('coinbase_commerce', 'coinbase_commerce\ProcessController@ipn')->name('coinbase_commerce');
    Route::get('mollie', 'mollie\ProcessController@ipn')->name('mollie');
    Route::post('cashmaal', 'cashmaal\ProcessController@ipn')->name('cashmaal');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetLinkEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify-code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.change-link');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware('admin')->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');

        Route::get('notification/read/{id}','AdminController@notificationRead')->name('notification.read');
        Route::get('notifications','AdminController@notifications')->name('notifications');

        // Users Manager
        Route::get('users', 'ManageUsersController@allUsers')->name('users.all');
        Route::get('users/active', 'ManageUsersController@activeUsers')->name('users.active');
        Route::get('users/banned', 'ManageUsersController@bannedUsers')->name('users.banned');
        Route::get('users/email-verified', 'ManageUsersController@emailVerifiedUsers')->name('users.emailVerified');
        Route::get('users/email-unverified', 'ManageUsersController@emailUnverifiedUsers')->name('users.emailUnverified');
        Route::get('users/sms-unverified', 'ManageUsersController@smsUnverifiedUsers')->name('users.smsUnverified');
        Route::get('users/sms-verified', 'ManageUsersController@smsVerifiedUsers')->name('users.smsVerified');

        Route::get('users/{scope}/search', 'ManageUsersController@search')->name('users.search');
        Route::get('user/detail/{id}', 'ManageUsersController@detail')->name('users.detail');
        Route::post('user/update/{id}', 'ManageUsersController@update')->name('users.update');
        Route::post('user/add-sub-balance/{id}', 'ManageUsersController@addSubBalance')->name('users.addSubBalance');
        Route::get('user/send-email/{id}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}', 'ManageUsersController@sendEmailSingle')->name('users.email.single');
        Route::get('user/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('user/deposits/{id}', 'ManageUsersController@deposits')->name('users.deposits');
        Route::get('user/deposits/via/{method}/{type?}/{userId}', 'ManageUsersController@depViaMethod')->name('users.deposits.method');
        Route::get('user/ads/{id}', 'ManageUsersController@userAds')->name('users.ads');
        Route::get('user/promoted-ads/{id}', 'ManageUsersController@userPromotedAds')->name('users.promoted.ads');
        // Login History
        Route::get('users/login/history/{id}', 'ManageUsersController@userLoginHistory')->name('users.login.history.single');

        Route::get('users/send-email', 'ManageUsersController@showEmailAllForm')->name('users.email.all');
        Route::post('users/send-email', 'ManageUsersController@sendEmailAll')->name('users.email.send');


        //category manage
       Route::get('/categories', 'CategoryController@allCategories')->name('categories');
       Route::post('/categories/store', 'CategoryController@store')->name('categories.store');
       Route::post('/categories/update/{id}', 'CategoryController@update')->name('categories.update');

       //subcategory
       Route::get('/sub-categories/{id}', 'SubCategoryController@allSubCategories')->name('subcategories');
       Route::post('/sub-category/store', 'SubCategoryController@store')->name('subcategories.store');
       Route::post('/sub-category/update/{id}', 'SubCategoryController@update')->name('subcategories.update');
       Route::get('/sub-category/fields/{id}', 'SubCategoryController@fields')->name('subcategories.fields');
       Route::post('/sub-category/fields/add', 'SubCategoryController@addFields')->name('subcategories.fields.add');

       Route::post('/sub-category/fields/remove/{id}', 'SubCategoryController@removeField')->name('subcategories.fields.remove');
       Route::get('/sub-category/fields/edit/{id}', 'SubCategoryController@editField')->name('subcategories.fields.edit');
       Route::post('/sub-category/fields/update/{id}', 'SubCategoryController@updateField')->name('subcategories.fields.update');

       //location manage
       //division
       Route::get('/location/divisions', 'DivisionController@divisions')->name('location.divisions');
       Route::post('/location/divisions/store', 'DivisionController@store')->name('location.divisions.store');
       Route::post('/location/divisions/update/{id}', 'DivisionController@update')->name('location.divisions.update');

       //district
       Route::get('/location/districts/{id}', 'DistrictController@districts')->name('location.districts');
       Route::post('/location/districts/store', 'DistrictController@store')->name('location.districts.store');
       Route::post('/location/districts/update/{id}', 'DistrictController@update')->name('location.districts.update');

       //package
       Route::get('/packages', 'PackageController@packages')->name('packages');
       Route::post('/packages/store', 'PackageController@store')->name('packages.store');
       Route::post('/packages/update/{id}', 'PackageController@update')->name('packages.update');

       //ad promotion
       Route::get('/ad-promotion/request/all', 'AdPromoteController@all')->name('ad.promote.all');
       Route::get('/ad-promotion/request/pending', 'AdPromoteController@pending')->name('ad.promote.pending');
       Route::get('/ad-promotion/request/accepted', 'AdPromoteController@accepted')->name('ad.promote.accepted');
       Route::get('/ad-promotion/request/rejected', 'AdPromoteController@rejected')->name('ad.promote.rejected');

Files/core/resources/views/admin/info.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="row">
        <div class="col-xl-12">
            <div class="card b-radius--10 ">
              <div class="card-body p-0">
                <div class="table-responsive">
                  <table class="table table--light style--two">
                    <tbody>
                      <tr>
                          <td>@lang('PHP Version')</td>
                          <td>{{ $currentPHP }}</td>
                      </tr>
                      <tr>
                          <td>@lang('Laravel Version')</td>
                          <td>{{ $laravelVersion }}</td>
                      </tr>
                      <tr>
                          <td>@lang('Server Software')</td>
                          <td>{{ @$serverDetails['SERVER_SOFTWARE'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('Server IP Address')</td>
                          <td>{{ @$serverDetails['SERVER_ADDR'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('Server Protocol')</td>
                          <td>{{ @$serverDetails['SERVER_PROTOCOL'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('HTTP Host')</td>
                          <td>{{ @$serverDetails['HTTP_HOST'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('Database Port')</td>
                          <td>{{ @$serverDetails['DB_PORT'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('App Environment')</td>
                          <td>{{ @$serverDetails['APP_ENV'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('App Debug')</td>
                          <td>{{ @$serverDetails['APP_DEBUG'] }}</td>
                      </tr>
                      <tr>
                          <td>@lang('Timezone')</td>
                          <td>{{ @$timeZone }}</td>
                      </tr>
                    </tbody>
                  </table><!-- table end -->
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection
@push('style')
<style>
  td{
    font-size: 22px !important;
  }
  .table td {
      white-space: nowrap;
  }
</style>
@endpush

Files/core/resources/views/admin/notifications.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="notify__area">
    	@foreach($notifications as $notification)
        <a class="notify__item @if($notification->read_status == 0) unread--notification @endif" href="{{ route('admin.notification.read',$notification->id) }}">
            <div class="notify__thumb bg--primary">
                <img src="{{ getImage(imagePath()['profile']['user']['path'].'/'.@$notification->user->image,imagePath()['profile']['user']['size'])}}">
            </div>
            <div class="notify__content">
                <h6 class="title">{{ __($notification->title) }}</h6>
                <span class="date"><i class="las la-clock"></i> {{ $notification->created_at->diffForHumans() }}</span>
            </div>
        </a>
        @endforeach
        {{ paginateLinks($notifications) }}
    </div>
@endsection

Files/core/resources/views/admin/packages.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row">

        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Package Name')</th>
                                <th scope="col">@lang('Price')</th>
                                <th scope="col">@lang('Validity')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($packages as $package)
                            <tr>
                                <td data-label="@lang('Subscription Name')"><span class="text--small badge font-weight-normal badge--success">{{$package->name}}</span></td>
                                <td data-label="@lang('Price')"><span class="badge badge-pill bg--primary">{{$general->cur_sym}} {{getAmount($package->price)}} {{$general->cur_text}}</span></td>
                                <td data-label="@lang('Validity')">{{$package->validity}} @lang('days')</td>
                                <td data-label="@lang('Status')">
                                    @if ($package->status == 1)
                                     <span class="text--small badge font-weight-normal badge--success">@lang('active')</span>
                                    @else
                                     <span class="text--small badge font-weight-normal badge--warning">@lang('inactive')</span>
                                    @endif
                                </td>
                                <td data-label="@lang('Action')">
                                    <a href="javascript:void(0)" class="icon-btn edit" data-package="{{$package}}" data-route="{{route('admin.packages.update',$package->id)}}" data-toggle="tooltip" title="@lang('Edit')">
                                        <i class="las la-edit text--shadow"></i>
                                    </a>
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                 
                </div>
            </div><!-- card end -->
        </div>


    </div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog" role="document">
      <form action="{{route('admin.packages.store')}}" method="POST">
        @csrf
        <div class="modal-content">
            <div class="modal-header bg--primary">
              <h5 class="modal-title text-white">@lang('Add Package')</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label >@lang('Name')</label>
                    <input class="form-control" type="text" name="name" placeholder="@lang('Package Name')" value="{{old('name')}}" required>
                </div>
                <div class="form-group">
                    <label >@lang('Price')</label>
                    <div class="input-group">
                       <input class="form-control" type="number" min="0" name="price" placeholder="@lang('Package Price')" value="{{old('price')}}" required>
                       <div class="input-group-append">
                           <span class="input-group-text">{{$general->cur_text}}</span>
                       </div>
                    </div>
                </div>
               
                <div class="form-group">
                    <label >@lang('Validity') <small>(@lang('in days'))</small></label>
                    <div class="input-group">
                       <input class="form-control" type="number" min="1" name="validity" placeholder="@lang('Package validity')" value="{{old('validity')}}" required>
                       <div class="input-group-append">
                           <span class="input-group-text">@lang('days')</span>
                       </div>
                    </div>
                </div>

                 <div class="form-group">
                     <label>@lang('Status')</label>
                     <input type="checkbox" data-width="100%" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('active')" data-off="@lang('inactive')" name="status">
                 </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Close')</button>
              <button type="submit" class="btn btn--primary">@lang('Submit')</button>
            </div>
          </div>
      </form>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog" role="document">
      <form action="" method="POST">
        @csrf
        <div class="modal-content">
            <div class="modal-header bg--primary">
              <h5 class="modal-title text-white">@lang('Edit Package')</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label >@lang('Name')</label>
                    <input class="form-control" type="text" name="name" placeholder="@lang('Package Name')" required>
                </div>
                <div class="form-group">
                    <label >@lang('Price')</label>
                    <div class="input-group">
                       <input class="form-control" type="number" min="0" name="price" placeholder="@lang('Package Price')" required>
                       <div class="input-group-append">
                           <span class="input-group-text">{{$general->cur_text}}</span>
                       </div>
                    </div>
                </div>
               
                <div class="form-group">
                    <label >@lang('Validity') <small>(@lang('in days'))</small></label>
                    <div class="input-group">
                       <input class="form-control" type="number" min="1" name="validity" placeholder="@lang('Package validity')" required>
                       <div class="input-group-append">
                           <span class="input-group-text">@lang('days')</span>
                       </div>
                    </div>
                </div>

                 <div class="form-group">
                     <label>@lang('Status')</label>
                     <input type="checkbox" data-width="100%" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('active')" data-off="@lang('inactive')" name="status">
                 </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('Close')</button>
              <button type="submit" class="btn btn--primary">@lang('Submit')</button>
            </div>
          </div>
      </form>
    </div>
</div>
@endsection



@push('breadcrumb-plugins')

<!-- Button trigger modal -->
<button type="button" class="btn btn--primary mr-3 mt-2" data-toggle="modal" data-target="#addModal">
  <i class="las la-plus"></i> @lang('Add Package')
</button>

<form action="" method="GET" class="form-inline float-sm-right bg--white mt-2">
     <div class="input-group has_append">
        <input type="text" name="search" class="form-control" placeholder="@lang('search by name')" value="{{$search??''}}">
          <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
          </div>
     </div>
</form>
@endpush

@push('script')

    <script>
        'use strict';
        (function ($) {
            $('.edit').on('click',function () { 
                var packages = $(this).data('package')
                var price = parseInt(packages.price)
                var route = $(this).data('route')
                $('#editModal').find('input[name=name]').val(packages.name)
                $('#editModal').find('input[name=price]').val(price.toFixed(2))
                $('#editModal').find('input[name=validity]').val(packages.validity)

                if(packages.status == 1){
                    $('#editModal').find('input[name=status]').bootstrapToggle('on')
                }
                $('#editModal').find('form').attr('action',route)
                $('#editModal').modal('show')
             })
        })(jQuery);
    </script>

@endpush

Files/core/resources/views/admin/password.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="row mb-none-30">
        <div class="col-lg-3 col-md-3 mb-30">

            <div class="card b-radius--5 overflow-hidden">
                <div class="card-body p-0">
                    <div class="d-flex p-3 bg--primary">
                        <div class="avatar avatar--lg">
                            <img src="{{ getImage(imagePath()['profile']['admin']['path'].'/'. $admin->image,imagePath()['profile']['admin']['size'])}}" alt="@lang('Image')">
                        </div>
                        <div class="pl-3">
                            <h4 class="text--white">{{__($admin->name)}}</h4>
                        </div>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Name')
                            <span class="font-weight-bold">{{ __($admin->name) }}</span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Username')
                            <span  class="font-weight-bold">{{ __($admin->username) }}</span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Email')
                            <span  class="font-weight-bold">{{ $admin->email }}</span>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-9 col-md-9 mb-30">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-50 border-bottom pb-2">@lang('Change Password')</h5>

                    <form action="{{ route('admin.password.update') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">@lang('Password')</label>
                            <div class="col-lg-9">

                                <input class="form-control" type="password" placeholder="@lang('Password')" name="old_password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">@lang('New Password')</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="password" placeholder="@lang('New Password')" name="password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">@lang('Confirm Password')</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="password" placeholder="@lang('Confirm Password')" name="password_confirmation">
                            </div>
                        </div>


                        <div class="form-group row">

                            <label class="col-lg-3 col-form-label form-control-label"></label>
                            <div class="col-lg-9">
                            <button type="submit" class="btn btn--primary btn-block btn-lg">@lang('Save Changes')</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('breadcrumb-plugins')
    <a href="{{route('admin.profile')}}" class="btn btn-sm btn--primary box--shadow1 text--small" ><i class="fa fa-user"></i>@lang('Profile Setting')</a>
@endpush

Files/core/resources/views/admin/profile.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row mb-none-30">
        <div class="col-lg-3 col-md-3 mb-30">

            <div class="card b-radius--5 overflow-hidden">
                <div class="card-body p-0">
                    <div class="d-flex p-3 bg--primary align-items-center">
                        <div class="avatar avatar--lg">
                            <img src="{{ getImage(imagePath()['profile']['admin']['path'].'/'. $admin->image,imagePath()['profile']['admin']['size'])}}" alt="@lang('Image')">
                        </div>
                        <div class="pl-3">
                            <h4 class="text--white">{{__($admin->name)}}</h4>
                        </div>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Name')
                            <span class="font-weight-bold">{{__($admin->name)}}</span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Username')
                            <span  class="font-weight-bold">{{__($admin->username)}}</span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Email')
                            <span  class="font-weight-bold">{{$admin->email}}</span>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-9 col-md-9 mb-30">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-50 border-bottom pb-2">@lang('Profile Information')</h5>

                    <form action="{{ route('admin.profile.update') }}" method="POST" enctype="multipart/form-data">
                        @csrf



                        <div class="row">

                            <div class="col-md-6">

                                <div class="form-group">
                                    <div class="image-upload">
                                        <div class="thumb">
                                            <div class="avatar-preview">
                                                <div class="profilePicPreview" style="background-image: url({{ getImage(imagePath()['profile']['admin']['path'].'/'.auth()->guard('admin')->user()->image,imagePath()['profile']['admin']['size']) }})">
                                                    <button type="button" class="remove-image"><i class="fa fa-times"></i></button>
                                                </div>
                                            </div>
                                            <div class="avatar-edit">
                                                <input type="file" class="profilePicUpload" name="image" id="profilePicUpload1" accept=".png, .jpg, .jpeg">
                                                <label for="profilePicUpload1" class="bg--success">@lang('Upload Image')</label>
                                                <small class="mt-2 text-facebook">@lang('Supported files'): <b>@lang('jpeg'), @lang('jpg').</b> @lang('Image will be resized into 400x400px') </small>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group ">
                                    <label class="form-control-label font-weight-bold">@lang('Name')</label>
                                    <input class="form-control" type="text" name="name" value="{{ auth()->guard('admin')->user()->name }}" >
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label  font-weight-bold">@lang('Email')</label>
                                    <input class="form-control" type="email" name="email" value="{{ auth()->guard('admin')->user()->email }}" >
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn--primary btn-block btn-lg">@lang('Save Changes')</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('breadcrumb-plugins')
    <a href="{{route('admin.password')}}" class="btn btn-sm btn--primary box--shadow1 text--small" ><i class="fa fa-key"></i>@lang('Password Setting')</a>
@endpush